# Generated by Django 3.2.4 on 2021-08-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(editable=False, max_length=70, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'registered_user',
            },
        ),
    ]
